import { BRAND, STEWARD } from "../brand.ts";
import type { Config } from "../config/index.ts";
import { humanDuration } from "../util/time.ts";
import { remediationOrder } from "../phases/p5-adjudicate.ts";
import type { RoiReport, TracedRange, Range } from "../roi/engine.ts";
import type { Assumptions } from "../roi/assumptions.ts";
import { bandLabel } from "../roi/assumptions.ts";
import type {
  AdversaryFinding, Gap, Obligation, ScanResult, ExcludedObligation, Adjudication,
} from "../schemas/index.ts";
import type { PreviewEntry } from "../sovereignty/index.ts";
import type { EgressRecord } from "../sovereignty/gate.ts";

const SEV_ICON: Record<string, string> = {
  critical: "🔴", high: "🟠", medium: "🟡", low: "🔵", info: "⚪",
};

const fmt = (n: number, digits = 0) =>
  n.toLocaleString("en-US", { minimumFractionDigits: digits, maximumFractionDigits: digits });

const range = (r: Range, digits = 0) =>
  r.low === r.high ? fmt(r.low, digits) : `${fmt(r.low, digits)}–${fmt(r.high, digits)}`;

function footer(): string {
  return (
    `\n---\n\n_${BRAND.disclaimer}_\n\n` +
    `_Generated by [${BRAND.display}](${STEWARD.url}) v${BRAND.version}. ${BRAND.tagline}_  \n` +
    `_${STEWARD.line}_\n`
  );
}

function banner(result: ScanResult): string {
  const lines: string[] = [];
  if (result.meta.incomplete) {
    lines.push(
      `> ⚠️ **This run is incomplete.** ` +
        result.meta.phases_skipped.map((p) => `Phase ${p.phase} was skipped: ${p.reason}.`).join(" ") +
        ` Everything not checked is listed below; absence of a finding in a skipped area is not evidence of compliance.`,
    );
  }
  if (result.meta.corpus_stale) {
    lines.push(
      `> ⚠️ **The legal corpus is stale.** Some obligations were served from cache past their freshness window. ` +
        `They are still reported, with their retrieval dates, because a stale citation you can check beats no citation — ` +
        `but re-run with network access before relying on this.`,
    );
  }
  if (result.meta.offline) {
    lines.push(`> ℹ️ This run was **offline**. Only the local phases ran.`);
  }
  return lines.length ? lines.join("\n>\n") + "\n\n" : "";
}

/* ───────────────────────────── REPORT.md ───────────────────────────── */

export function renderReport(result: ScanResult, cfg: Config): string {
  const { meta, profile, gaps, obligations, adversary, evidence } = result;
  const out: string[] = [];

  out.push(`# Compliance report — ${cfg.project.name}`);
  out.push("");
  out.push(banner(result));

  /* 1. scope and limitations */
  out.push(`## 1. Scope and limitations`);
  out.push("");
  out.push(
    `This report was produced by ${BRAND.display}, a static analysis tool. It reads code and retrieves law. ` +
      `It does not read your contracts, your production configuration, or your database contents, and it is ` +
      `not legal advice.`,
  );
  out.push("");
  out.push(`| | |`);
  out.push(`|---|---|`);
  out.push(`| Regions audited | ${meta.regions.join(", ") || "none"} |`);
  out.push(`| Files scanned | ${evidence.file_count} (${fmt(evidence.loc)} lines) |`);
  out.push(`| Obligations retrieved | ${obligations.length} |`);
  out.push(`| Gaps found | ${gaps.length} |`);
  out.push(`| Sovereignty level | ${meta.sovereignty_level} (${["structural", "pseudonymised", "verbatim"][meta.sovereignty_level]}) |`);
  out.push(`| Run duration | ${humanDuration(meta.duration_ms)} |`);
  out.push(`| API spend | $${Object.values(meta.cost_usd).reduce((a, b) => a + b, 0).toFixed(4)} |`);
  out.push("");
  out.push(`**What this report does not cover:**`);
  out.push("");
  for (const item of [
    "The adequacy of any document — only whether one exists.",
    "Organisational measures: training, access reviews, vendor due diligence, accountability.",
    "Anything outside the scanned paths, including infrastructure configured in a cloud console.",
    "Regimes with no shipped pack. Those are listed in `obligations.excluded.json` with reasons.",
  ]) {
    out.push(`- ${item}`);
  }
  out.push("");

  /* 2. system profile and contradictions */
  out.push(`## 2. System profile`);
  out.push("");
  out.push(profile.summary);
  out.push("");
  out.push(`- **Roles:** ${profile.roles.join(", ") || "unclear"}`);
  out.push(`- **Data subjects:** ${profile.data_subjects.join(", ") || "not established"}`);
  out.push(`- **Languages:** ${profile.languages.join(", ") || "none detected"}`);
  out.push(`- **Frameworks:** ${profile.frameworks.join(", ") || "none detected"}`);
  out.push(`- **Data stores:** ${profile.data_stores.join(", ") || "none detected"}`);
  out.push("");

  if (profile.data_categories.length) {
    out.push(`### Data categories`);
    out.push("");
    out.push(`| Category | Special | Evidence |`);
    out.push(`|---|---|---|`);
    for (const c of profile.data_categories) {
      out.push(`| ${c.name} | ${c.special ? "**yes**" : "no"} | ${c.evidence.slice(0, 3).join(", ") || "—"} |`);
    }
    out.push("");
  }

  if (profile.contradictions.length) {
    out.push(`### Unresolved contradictions`);
    out.push("");
    out.push(
      `The description and the code disagree. Each of these changes which obligations apply, so resolving ` +
        `them is the highest-value thing you can do with this report.`,
    );
    out.push("");
    for (const c of profile.contradictions) {
      out.push(`**${c.id} — ${c.severity === "blocking" ? "🔴 blocking" : "🟡 warning"}**`);
      out.push("");
      out.push(`- **Claim:** ${c.claim}`);
      out.push(`- **Evidence:** ${c.evidence}`);
      out.push(`- **Question:** ${c.question}`);
      out.push("");
    }
  }

  if (profile.open_questions.length) {
    out.push(`### Open questions`);
    out.push("");
    for (const q of profile.open_questions) {
      out.push(`- **${q.id}.** ${q.question}  \n  _Why it matters:_ ${q.why_it_matters}`);
    }
    out.push("");
  }

  /* 3. regions and regimes */
  out.push(`## 3. Regions and regimes`);
  out.push("");
  out.push(`| Region | Obligations | Double-sourced | Disputed |`);
  out.push(`|---|---|---|---|`);
  const byRegion = new Map<string, Obligation[]>();
  for (const o of obligations) {
    if (!byRegion.has(o.region)) byRegion.set(o.region, []);
    byRegion.get(o.region)!.push(o);
  }
  for (const [region, list] of [...byRegion].sort()) {
    const double = list.filter((o) => o.verification === "double_sourced").length;
    const disp = result.disputed.filter((o) => o.region === region).length;
    out.push(`| ${region} | ${list.length} | ${double} | ${disp} |`);
  }
  out.push("");

  /* 4. gap summary */
  out.push(`## 4. Gap summary`);
  out.push("");
  if (!gaps.length) {
    out.push(
      `No gaps were raised. That is not the same as compliant: check the indeterminate items in section 7 ` +
        `and the obligations excluded in \`obligations.excluded.json\` before drawing any conclusion.`,
    );
    out.push("");
  } else {
    out.push(`| ID | Sev | Title | Regions | Effort | Owner |`);
    out.push(`|---|---|---|---|---|---|`);
    for (const g of gaps) {
      out.push(
        `| [${g.id}](#${g.id.toLowerCase()}) | ${SEV_ICON[g.severity]} ${g.severity} | ${escapePipes(g.title)} | ` +
          `${g.regions.join(", ")} | ${g.manual_fix.effort.engineering_days}d${g.manual_fix.effort.legal_review ? " + legal" : ""} | ${g.owner_hint} |`,
      );
    }
    out.push("");
  }

  /* 5. gaps in full */
  if (gaps.length) {
    out.push(`## 5. Gaps in full`);
    out.push("");
    for (const g of gaps) out.push(renderGap(g, obligations));
  }

  /* 6. security and stress findings */
  out.push(`## 6. Security findings`);
  out.push("");
  if (!adversary.length) {
    out.push(
      `Phase 4 produced no findings${meta.phases_skipped.some((p) => p.phase === 4) ? ", because it was skipped" : ""}. ` +
        `Treat the security posture as unassessed rather than clean.`,
    );
    out.push("");
  } else {
    out.push(
      `Findings below include those with no legal hook, because a vulnerability does not stop being a ` +
        `vulnerability when no statute names it.`,
    );
    out.push("");
    out.push(`| ID | Sev | Category | Finding | Location | Status |`);
    out.push(`|---|---|---|---|---|---|`);
    for (const f of adversary) {
      out.push(
        `| ${f.id} | ${SEV_ICON[f.severity]} ${f.severity} | ${f.category}${f.owasp_llm ? ` (${f.owasp_llm})` : ""} | ` +
          `${escapePipes(f.title)} | \`${f.location}\` | ${f.status} |`,
      );
    }
    out.push("");
    for (const f of adversary.filter((x) => x.severity === "critical" || x.severity === "high")) {
      out.push(`#### ${f.id} — ${f.title}`);
      out.push("");
      out.push(`- **Condition:** ${f.condition}`);
      out.push(`- **Impact:** ${f.impact}`);
      if (f.confirmation_steps.length) {
        out.push(`- **Confirm it yourself:**`);
        for (const s of f.confirmation_steps) out.push(`  1. ${s}`);
      }
      out.push("");
    }
  }

  /* 7. disputed and indeterminate */
  out.push(`## 7. Disputed and indeterminate items`);
  out.push("");
  const indeterminate = result.adjudications.filter((a) => a.status === "indeterminate");
  if (result.disputed.length) {
    out.push(`### Disputed obligations`);
    out.push("");
    out.push(
      `Two independent retrievals disagreed about these provisions. They are reported here and are **not** ` +
        `counted as gaps — a provision we cannot confirm is not a provision we will hold you to.`,
    );
    out.push("");
    for (const o of result.disputed) {
      out.push(`- **${o.instrument} ${o.provision}** — ${o.title}. Sources: ${o.citations.map((c) => `[link](${c.url})`).join(", ")}`);
    }
    out.push("");
  }
  if (indeterminate.length) {
    out.push(`### Indeterminate obligations (${indeterminate.length})`);
    out.push("");
    out.push(`These could not be decided from code alone. Each states what would resolve it.`);
    out.push("");
    for (const a of indeterminate.slice(0, 40)) {
      const ob = obligations.find((o) => o.id === a.obligation_id);
      out.push(`- **${ob?.instrument ?? a.obligation_id} ${ob?.provision ?? ""}** — ${ob?.title ?? ""}`);
      out.push(`  - _Why undecidable:_ ${a.rationale}`);
      out.push(`  - _Resolved by:_ ${a.resolving_evidence ?? "not stated"}`);
    }
    out.push("");
  }
  if (!result.disputed.length && !indeterminate.length) {
    out.push(`None.`);
    out.push("");
  }

  /* 8. exposure ledger */
  out.push(`## 8. Exposure ledger`);
  out.push("");
  out.push(renderLedgerBody(result));

  /* 9. remediation plan */
  if (gaps.length) {
    out.push(`## 9. Remediation plan`);
    out.push("");
    out.push(`In dependency order. Each step names the gap, the effort, and who needs to be in the room.`);
    out.push("");
    for (const [i, g] of remediationOrder(gaps).entries()) {
      out.push(
        `${i + 1}. **${g.id}** ${SEV_ICON[g.severity]} — ${g.manual_fix.what}  \n` +
          `   _${g.manual_fix.effort.engineering_days} engineering day(s)` +
          `${g.manual_fix.effort.legal_review ? ", needs legal review" : ""}` +
          `${g.manual_fix.effort.vendor_action ? ", needs vendor action" : ""}` +
          `${g.dependencies.length ? `, after ${g.dependencies.join(", ")}` : ""}._`,
      );
    }
    out.push("");
  }

  /* 10. citations */
  out.push(`## 10. Citations`);
  out.push("");
  out.push(renderCitationsBody(obligations));

  /* 11. run metadata */
  out.push(`## 11. Run metadata and reproduction`);
  out.push("");
  out.push("```json");
  out.push(JSON.stringify(meta, null, 2));
  out.push("```");
  out.push("");
  out.push(`Reproduce this run:`);
  out.push("");
  out.push("```bash");
  out.push(`${BRAND.name} report --format md   # re-render from cache, no model calls`);
  out.push(`${BRAND.name} scan --resume ${meta.run_id}`);
  out.push("```");
  out.push(footer());

  return out.join("\n");
}

function renderGap(g: Gap, obligations: Obligation[]): string {
  const out: string[] = [];
  const obs = g.obligations.map((id) => obligations.find((o) => o.id === id)).filter(Boolean) as Obligation[];

  out.push(`### ${g.id} — ${g.title}`);
  out.push("");
  out.push(
    `${SEV_ICON[g.severity]} **${g.severity.toUpperCase()}** · status: ${g.status} · confidence: ${(g.confidence * 100).toFixed(0)}% · ` +
      `regions: ${g.regions.join(", ")} · owner: ${g.owner_hint}`,
  );
  out.push("");
  out.push(`_Severity basis: ${g.severity_basis.join(", ")}._`);
  out.push("");

  out.push(`#### What`);
  out.push("");
  out.push(g.manual_fix.what);
  out.push("");

  out.push(`#### Why`);
  out.push("");
  out.push(`**Legally:** ${g.manual_fix.why.legal}`);
  out.push("");
  out.push(`**In engineering terms:** ${g.manual_fix.why.engineering}`);
  out.push("");
  if (obs.length) {
    out.push(`**Obligations relied on:**`);
    out.push("");
    for (const o of obs) {
      out.push(
        `- ${o.instrument} ${o.provision} — ${o.title}  \n` +
          `  ${o.citations.map((c) => `[${c.primary ? "primary" : "commentary"}](${c.url})`).join(" · ")}` +
          ` · retrieved ${o.citations[0]?.retrieved_at.slice(0, 10) ?? "unknown"} · ${o.verification}`,
      );
    }
    out.push("");
  }
  if (g.manual_fix.why.file_refs.length) {
    out.push(`**Where:** ${g.manual_fix.why.file_refs.map((f) => `\`${f}\``).join(", ")}`);
    out.push("");
  }

  out.push(`#### How`);
  out.push("");
  for (const [i, step] of g.manual_fix.how.entries()) {
    out.push(`${i + 1}. ${step.replace(/^\d+\.\s*/, "")}`);
  }
  out.push("");

  out.push(`#### Consequence`);
  out.push("");
  out.push(`**If unfixed:** ${g.manual_fix.consequence.if_unfixed}`);
  out.push("");
  out.push(`**If fixed:** ${g.manual_fix.consequence.if_fixed}`);
  out.push("");
  out.push(`**Residual risk:** ${g.manual_fix.consequence.residual_risk}`);
  out.push("");

  const max = g.exposure.financial.statutory_maximum;
  out.push(`#### Exposure`);
  out.push("");
  if (max) {
    out.push(
      `- **Statutory maximum:** ${max.currency} ${fmt(max.amount)}` +
        (max.or_percent_turnover ? ` or ${max.or_percent_turnover}% of turnover, whichever is higher` : "") +
        ` — [source](${max.citation.url})`,
    );
  } else {
    out.push(`- **Statutory maximum:** not quantified — the cited instrument does not state a figure for this provision.`);
  }
  const nf = g.exposure.non_financial;
  for (const [key, label] of [
    ["market_access", "Market access"],
    ["contract_risk", "Contract risk"],
    ["operational", "Operational"],
    ["personal_liability", "Personal liability"],
    ["reputational", "Reputational"],
    ["timeline_risk", "Timeline risk"],
  ] as const) {
    const v = nf[key];
    if (v) out.push(`- **${label}:** ${v}`);
  }
  out.push("");

  out.push(`#### Verify the fix`);
  out.push("");
  out.push("```bash");
  for (const v of g.manual_fix.verify) out.push(v);
  out.push("```");
  out.push("");

  out.push(`<details><summary>Agent prompt for ${g.id} — paste into any coding agent</summary>`);
  out.push("");
  out.push("````text");
  out.push(g.agent_prompt);
  out.push("````");
  out.push("");
  out.push(`</details>`);
  out.push("");

  return out.join("\n");
}

function escapePipes(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

/* ───────────────────────────── EXECUTIVE_SUMMARY.md ───────────────────────────── */

export function renderExecutiveSummary(result: ScanResult, cfg: Config, roi: RoiReport | null): string {
  const { gaps, obligations, meta } = result;
  const bySev: Record<string, number> = {};
  for (const g of gaps) bySev[g.severity] = (bySev[g.severity] ?? 0) + 1;

  const out: string[] = [];
  out.push(`# Executive summary — ${cfg.project.name}`);
  out.push("");
  out.push(banner(result));
  out.push(
    `${BRAND.display} audited ${result.evidence.file_count} files against ${obligations.length} obligations ` +
      `retrieved from ${new Set(obligations.map((o) => o.region)).size} regime(s), and found **${gaps.length} gap(s)**.`,
  );
  out.push("");

  if (gaps.length) {
    out.push(
      `${Object.entries(bySev)
        .map(([s, n]) => `${SEV_ICON[s]} ${n} ${s}`)
        .join(" · ")}`,
    );
    out.push("");
    out.push(`## The three that matter most`);
    out.push("");
    for (const g of gaps.slice(0, 3)) {
      out.push(`**${g.id} — ${g.title}**`);
      out.push("");
      out.push(`${g.manual_fix.what}`);
      out.push("");
      out.push(`_If unfixed:_ ${g.manual_fix.consequence.if_unfixed}`);
      out.push("");
    }
  }

  const blocking = result.profile.contradictions.filter((c) => c.severity === "blocking");
  if (blocking.length) {
    out.push(`## Answer these first`);
    out.push("");
    out.push(
      `${blocking.length} contradiction(s) between your description and your code change which obligations ` +
        `apply. Until they are resolved, the rest of this report rests on an assumption.`,
    );
    out.push("");
    for (const c of blocking) out.push(`- ${c.question}`);
    out.push("");
  }

  if (roi) {
    out.push(`## What this cost and replaced`);
    out.push("");
    out.push(roi.headline);
    out.push("");
  }

  out.push(`## What still needs a human`);
  out.push("");
  for (const item of (roi?.not_done ?? []).slice(0, 4)) out.push(`- ${item}`);
  out.push("");
  out.push(`Full detail: \`compliance/REPORT.md\`. Exposure: \`compliance/LEDGER.md\`. ROI: \`compliance/ROI.md\`.`);
  out.push(`Run id \`${meta.run_id}\`.`);
  out.push(footer());
  return out.join("\n");
}

/* ───────────────────────────── LEDGER.md ───────────────────────────── */

export function renderLedger(result: ScanResult, cfg: Config): string {
  return (
    `# Legal exposure ledger — ${cfg.project.name}\n\n` +
    banner(result) +
    renderLedgerBody(result) +
    footer()
  );
}

/**
 * §7 — three buckets always: quantified (cited), qualitative (real but
 * unquantified), unknown (say so). Maxima are NEVER summed into a headline.
 */
function renderLedgerBody(result: ScanResult): string {
  const { gaps } = result;
  const out: string[] = [];

  const quantified = gaps.filter((g) => g.exposure.financial.statutory_maximum !== null);
  const qualitative = gaps.filter(
    (g) =>
      g.exposure.financial.statutory_maximum === null &&
      Object.values(g.exposure.non_financial).some((v) => v !== null),
  );
  const unknown = gaps.filter(
    (g) =>
      g.exposure.financial.statutory_maximum === null &&
      !Object.values(g.exposure.non_financial).some((v) => v !== null),
  );

  out.push(
    `> **These figures are not added up.** Regulators do not stack statutory maxima across regimes, and a ` +
      `headline total would be a fiction. Each maximum below is the ceiling for one provision in one regime, ` +
      `taken from the cited instrument.`,
  );
  out.push("");

  out.push(`### Quantified — cited statutory maxima (${quantified.length})`);
  out.push("");
  if (!quantified.length) {
    out.push(`None. No gap in this run maps to a provision whose cited instrument states a monetary maximum.`);
  } else {
    out.push(`| Gap | Regime | Statutory maximum | Source |`);
    out.push(`|---|---|---|---|`);
    for (const g of quantified) {
      const m = g.exposure.financial.statutory_maximum!;
      out.push(
        `| ${g.id} | ${g.regions.join(", ")} | ${m.currency} ${fmt(m.amount)}` +
          `${m.or_percent_turnover ? ` or ${m.or_percent_turnover}% turnover` : ""} | [cited](${m.citation.url}) |`,
      );
    }
  }
  out.push("");

  out.push(`### Qualitative — real but unquantified (${qualitative.length})`);
  out.push("");
  if (!qualitative.length) {
    out.push(`None.`);
  } else {
    for (const g of qualitative) {
      out.push(`**${g.id} — ${g.title}**`);
      out.push("");
      for (const [key, v] of Object.entries(g.exposure.non_financial)) {
        if (v) out.push(`- _${key.replace(/_/g, " ")}:_ ${v}`);
      }
      out.push("");
    }
  }

  out.push(`### Unknown — not quantified, and we say so (${unknown.length})`);
  out.push("");
  if (!unknown.length) {
    out.push(`None.`);
  } else {
    for (const g of unknown) {
      out.push(
        `- **${g.id}** — ${g.title}. No cited monetary maximum and no quantified non-financial consequence. ` +
          `The obligation is unsatisfied; what it costs you depends on facts this tool cannot see.`,
      );
    }
  }
  out.push("");

  const avoidable = gaps.flatMap((g) => g.exposure.financial.avoidable_costs.map((c) => ({ gap: g.id, ...c })));
  if (avoidable.length) {
    out.push(`### Avoidable costs`);
    out.push("");
    out.push(`| Gap | Item | Estimate |`);
    out.push(`|---|---|---|`);
    for (const c of avoidable) {
      out.push(`| ${c.gap} | ${escapePipes(c.item)} | ${c.estimate_days ? `${c.estimate_days} day(s)` : (c.note ?? "not quantified")} |`);
    }
    out.push("");
  }

  return out.join("\n");
}

/* ───────────────────────────── ROI.md ───────────────────────────── */

export function renderRoi(roi: RoiReport, cfg: Config, a: Assumptions): string {
  const out: string[] = [];
  const cur = roi.currency;

  out.push(`# ROI — ${cfg.project.name}`);
  out.push("");
  out.push(`## ${roi.headline}`);
  out.push("");
  out.push(
    `_Assumption set in force: **${roi.assumptions_customised ? "your edited roi.assumptions.yaml" : "shipped defaults"}**. ` +
      `Every figure below is a range, and every range names the assumption that produced it. ` +
      `Edit \`compliance/roi.assumptions.yaml\` and re-run \`${BRAND.name} roi\` to change any of it._`,
  );
  out.push("");

  /* 2. spend */
  out.push(`## 1. What it cost`);
  out.push("");
  out.push(
    `**$${roi.spend.total_usd.toFixed(4)}** in API spend` +
      (roi.spend.reported_by_vendor
        ? ` — reported by OpenRouter's own usage accounting, not estimated.`
        : ` — estimated from token counts, because the vendor did not report a cost for these calls.`),
  );
  out.push("");
  out.push(`| Seat | Spend |`);
  out.push(`|---|---|`);
  for (const [seat, v] of Object.entries(roi.spend.by_seat)) out.push(`| ${seat} | $${v.toFixed(4)} |`);
  out.push("");
  out.push(`| Phase | Spend |`);
  out.push(`|---|---|`);
  for (const [phase, v] of Object.entries(roi.spend.by_phase).sort()) out.push(`| phase ${phase} | $${v.toFixed(4)} |`);
  out.push("");
  out.push(`Your time: **${roi.spend.wall_clock_minutes} minutes** of wall clock, measured by the tool timing its own run.`);
  out.push("");

  /* 3. alternatives */
  out.push(`## 2. What it replaced`);
  out.push("");
  out.push(`| Alternative | Produces | Would not produce | Cost | Time |`);
  out.push(`|---|---|---|---|---|`);
  for (const alt of roi.money_saved.alternatives) {
    out.push(
      `| ${alt.name}${alt.unsourced ? " *" : ""} | ${escapePipes(alt.produces)} | ${escapePipes(alt.would_not_produce)} | ` +
        `${alt.cost_label} | ${range(alt.days)} days |`,
    );
  }
  out.push("");
  out.push(`_\\* cost basis is an unsourced assumption — see section 6._`);
  out.push("");

  /* 4. time saved */
  out.push(`## 3. What it saved in time`);
  out.push("");
  out.push(`Derived from this run's own counts, not from vibes.`);
  out.push("");
  out.push(`| Work | Counted artifact | Hours saved | Assumption |`);
  out.push(`|---|---|---|---|`);
  const row = (label: string, t: TracedRange) =>
    out.push(`| ${label} | ${t.basis} | ${range(t, 1)} | \`${t.assumption}\`${t.unsourced ? " (unsourced)" : ""} |`);
  row("Statute research", roi.time_saved.research_hours);
  row("Code review", roi.time_saved.review_hours);
  row("Writing remediation specs", roi.time_saved.remediation_spec_hours);
  out.push(`| **Total** | | **${range(roi.time_saved.total_hours, 1)}** | |`);
  out.push("");
  out.push(
    `The ${roi.counts.agent_prompts_generated} agent prompt(s) are not counted above. They convert remediation ` +
      `*specification* time into remediation *execution* time, which is a different saving and one this tool ` +
      `has no honest way to size.`,
  );
  out.push("");

  /* 5. exposure avoided */
  out.push(`## 4. What it saved by solving rather than not solving`);
  out.push("");
  out.push(
    `${roi.exposure.gaps_with_cited_maximum} gap(s) map to a provision with a cited statutory maximum; ` +
      `${roi.exposure.unquantified_gaps} do not and are reported as "not quantified". ` +
      `${roi.exposure.qualitative_items} qualitative consequence(s) are recorded in the ledger.`,
  );
  out.push("");
  if (roi.exposure.cited_maxima.length) {
    out.push(`| Gap | Cited maximum | Source |`);
    out.push(`|---|---|---|`);
    for (const m of roi.exposure.cited_maxima) {
      out.push(`| ${m.gap_id} | ${m.currency} ${fmt(m.amount)} | [cited](${m.citation}) |`);
    }
    out.push("");
    out.push(
      `**These are not added together.** See \`LEDGER.md\` for why a stacked total would be a fiction.`,
    );
    out.push("");
  }

  /* 6. retrofit */
  out.push(`## 5. Fix now vs fix after launch`);
  out.push("");
  out.push(
    `${roi.retrofit.pre_launch_gaps} of ${roi.counts.gaps} gap(s) are cheaper to fix before launch than after. ` +
      `Fixing everything now is estimated at **${range(roi.retrofit.engineering_days_now, 1)} engineering day(s)**. ` +
      `The same work after launch is estimated at **${range(roi.retrofit.engineering_days_after_launch, 1)} day(s)**, ` +
      `using the \`retrofit_multiplier\` assumption` +
      `${roi.retrofit.engineering_days_after_launch.unsourced ? " (unsourced)" : ""}.`,
  );
  out.push("");
  out.push(
    `The multiplier exists because a data-architecture problem found after launch has to be fixed *and* ` +
      `unwound: data already collected under the wrong basis, subjects already told the wrong thing, backups ` +
      `already written. That is where the real number lives for a pre-production team.`,
  );
  out.push("");

  /* 7. what it did not do — mandatory */
  out.push(`## 6. What ${BRAND.display} did **not** do`);
  out.push("");
  out.push(`This section is mandatory, and it is what makes the rest of this document believable.`);
  out.push("");
  for (const item of roi.not_done) out.push(`- ${item}`);
  out.push("");

  /* 8. assumptions */
  out.push(`## 7. Assumptions in force`);
  out.push("");
  if (roi.unsourced_assumptions.length) {
    out.push(
      `⚠️ **${roi.unsourced_assumptions.length} assumption(s) below are unsourced**: ` +
        `${roi.unsourced_assumptions.map((k) => `\`${k}\``).join(", ")}. ` +
        `They are shipped defaults, not researched figures. Replace the ones that matter to you.`,
    );
    out.push("");
  }
  out.push(`| Assumption | Value | Source |`);
  out.push(`|---|---|---|`);
  for (const [k, v] of Object.entries(a.rates)) {
    out.push(`| \`rates.${k}\` | ${bandLabel(v)} | ${v.source ?? "unsourced"} |`);
  }
  out.push(`| \`research_minutes_per_obligation\` | ${bandLabel(a.research_minutes_per_obligation, " min")} | ${a.research_minutes_per_obligation.source ?? "unsourced"} |`);
  out.push(`| \`review_minutes_per_path\` | ${bandLabel(a.review_minutes_per_path, " min")} | ${a.review_minutes_per_path.source ?? "unsourced"} |`);
  out.push(`| \`hours_to_write_remediation_spec\` | ${bandLabel(a.hours_to_write_remediation_spec, " h")} | ${a.hours_to_write_remediation_spec.source ?? "unsourced"} |`);
  out.push(`| \`retrofit_multiplier\` | ${bandLabel(a.retrofit_multiplier, "×")} | ${a.retrofit_multiplier.source ?? "unsourced"} |`);
  out.push("");
  out.push(`Edit \`compliance/roi.assumptions.yaml\`, then:`);
  out.push("");
  out.push("```bash");
  out.push(`${BRAND.name} roi --assumptions compliance/roi.assumptions.yaml`);
  out.push("```");
  out.push("");
  if (roi.hours_only) {
    out.push(
      `_Student profile: your labour is valued at zero currency and reported purely in hours. A student's ROI ` +
        `is time and learning, and pretending otherwise would be dishonest._`,
    );
    out.push("");
  }
  out.push(footer());
  return out.join("\n");
}

/* ───────────────────────────── citations.md ───────────────────────────── */

export function renderCitations(obligations: Obligation[]): string {
  return `# Citations\n\n` + renderCitationsBody(obligations) + footer();
}

function renderCitationsBody(obligations: Obligation[]): string {
  const out: string[] = [];
  out.push(
    `Every obligation reported carries at least one resolving primary source. Commentary can support a point ` +
      `but never establishes one.`,
  );
  out.push("");
  const byRegime = new Map<string, Obligation[]>();
  for (const o of obligations) {
    if (!byRegime.has(o.regime)) byRegime.set(o.regime, []);
    byRegime.get(o.regime)!.push(o);
  }
  for (const [regime, list] of [...byRegime].sort()) {
    out.push(`### ${regime}`);
    out.push("");
    for (const o of list) {
      out.push(`**${o.instrument} — ${o.provision}** (${o.verification}, confidence ${(o.confidence * 100).toFixed(0)}%)`);
      out.push("");
      for (const c of o.citations) {
        const quote = c.quote_verified === true ? " ✓ quote verified" : c.quote_verified === false ? " ⚠️ quote could not be verified against the source" : "";
        out.push(`- [${c.title}](${c.url}) — ${c.primary ? "**primary**" : "commentary"}, retrieved ${c.retrieved_at.slice(0, 10)}${quote}`);
      }
      out.push("");
    }
  }
  return out.join("\n");
}

/* ───────────────────────────── SOVEREIGNTY.md ───────────────────────────── */

export function renderSovereignty(
  preview: PreviewEntry[],
  egress: EgressRecord[],
  level: number,
  mapSize: number,
): string {
  const out: string[] = [];
  const sent = preview.filter((p) => p.status === "sent");
  const denied = preview.filter((p) => p.status === "denied");
  const totalOriginal = sent.reduce((n, p) => n + p.original_bytes, 0);
  const totalSealed = sent.reduce((n, p) => n + p.sealed_bytes, 0);
  const identifiers = sent.reduce((n, p) => n + (p.identifiers_mapped ?? 0), 0);
  const literals = sent.reduce((n, p) => n + (p.literals_placeheld ?? 0), 0);
  const dropped = sent.reduce((n, p) => n + (p.literals_dropped ?? 0), 0);

  out.push(`# What left this machine, and in what form`);
  out.push("");
  out.push(
    `Sovereignty level **${level}** (${["structural", "pseudonymised", "verbatim"][level]}). ` +
      `${mapSize} identifier(s) were mapped through a pseudonym table that lives at \`.addgp/sovereign/map.json\`, ` +
      `is mode 0600, is gitignored, and **was never included in any payload**.`,
  );
  out.push("");
  out.push(
    `The vendors received a structurally faithful but unidentifiable version of this codebase. Reassembling ` +
      `your product from it would require the map, which never left this laptop.`,
  );
  out.push("");

  out.push(`## Summary`);
  out.push("");
  out.push(`| | |`);
  out.push(`|---|---|`);
  out.push(`| Files sent (redacted) | ${sent.length} |`);
  out.push(`| Files refused outright | ${denied.length} |`);
  out.push(`| Original bytes | ${fmt(totalOriginal)} |`);
  out.push(`| Bytes actually sent | ${fmt(totalSealed)} |`);
  out.push(`| Identifiers pseudonymised | ${fmt(identifiers)} |`);
  out.push(`| Literals replaced with typed placeholders | ${fmt(literals)} |`);
  out.push(`| Literals dropped entirely (secret-matching) | ${fmt(dropped)} |`);
  out.push(`| Outbound requests | ${egress.length} |`);
  out.push(`| Distinct destinations | ${new Set(egress.map((e) => e.destination)).size} |`);
  out.push("");

  if (denied.length) {
    out.push(`## Refused outright — never read for egress`);
    out.push("");
    out.push(`| File | Reason |`);
    out.push(`|---|---|`);
    for (const d of denied.slice(0, 60)) out.push(`| \`${d.path}\` | ${d.reason} |`);
    if (denied.length > 60) out.push(`| …and ${denied.length - 60} more | |`);
    out.push("");
  }

  if (egress.length) {
    out.push(`## Egress ledger`);
    out.push("");
    out.push(`| Time | Phase | Destination | Bytes | Payload SHA-256 | Files covered |`);
    out.push(`|---|---|---|---|---|---|`);
    for (const e of egress.slice(-100)) {
      out.push(
        `| ${e.ts.slice(11, 19)} | ${e.phase} | ${e.destination} | ${fmt(e.bytes)} | \`${e.payload_sha256.slice(0, 12)}…\` | ${e.files_represented.length} |`,
      );
    }
    out.push("");
    out.push(`_Full ledger, including the real paths each payload covered: \`.addgp/egress.jsonl\`._`);
    out.push("");
  }

  out.push(`## Verify this yourself`);
  out.push("");
  out.push("```bash");
  out.push(`${BRAND.name} sovereignty preview      # exactly what would be sent, per file, before any call`);
  out.push(`${BRAND.name} sovereignty map          # the local pseudonym table`);
  out.push(`${BRAND.name} sovereignty ledger       # every outbound byte this tool has ever sent`);
  out.push("```");
  out.push(footer());
  return out.join("\n");
}

/* ───────────────────────────── excluded obligations ───────────────────────────── */

export function renderExcluded(excluded: ExcludedObligation[]): string {
  const out: string[] = [];
  out.push(`# Obligations excluded, with reasons`);
  out.push("");
  out.push(
    `"Why doesn't this apply to me?" is an audit question, so every exclusion is recorded rather than ` +
      `silently dropped.`,
  );
  out.push("");
  if (!excluded.length) {
    out.push(`Nothing was excluded in this run.`);
    return out.join("\n") + footer();
  }
  const byReason = new Map<string, ExcludedObligation[]>();
  for (const e of excluded) {
    if (!byReason.has(e.reason_code)) byReason.set(e.reason_code, []);
    byReason.get(e.reason_code)!.push(e);
  }
  for (const [code, list] of byReason) {
    out.push(`## ${code.replace(/_/g, " ")} (${list.length})`);
    out.push("");
    for (const e of list) out.push(`- **${e.title}** (${e.regime}) — ${e.reason}`);
    out.push("");
  }
  return out.join("\n") + footer();
}

export function renderAdjudicationsTable(adjudications: Adjudication[]): string {
  const counts: Record<string, number> = {};
  for (const a of adjudications) counts[a.status] = (counts[a.status] ?? 0) + 1;
  return Object.entries(counts)
    .map(([k, v]) => `${k}: ${v}`)
    .join(", ");
}

export function renderAdversaryOnly(findings: AdversaryFinding[]): string {
  const out = [`# Security and stress findings`, ""];
  for (const f of findings) {
    out.push(`## ${f.id} — ${f.title}`);
    out.push("");
    out.push(`${SEV_ICON[f.severity]} ${f.severity} · ${f.category}${f.owasp_llm ? ` · ${f.owasp_llm}` : ""}${f.cwe ? ` · ${f.cwe}` : ""} · ${f.status}`);
    out.push("");
    out.push(`- **Location:** \`${f.location}\``);
    out.push(`- **Condition:** ${f.condition}`);
    out.push(`- **Impact:** ${f.impact}`);
    if (f.confirmation_steps.length) {
      out.push(`- **Confirm:**`);
      for (const s of f.confirmation_steps) out.push(`  1. ${s}`);
    }
    out.push("");
  }
  return out.join("\n") + footer();
}
